In [1]:
from bs4 import BeautifulSoup
from seleniumwire import webdriver
import pandas as pd
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
from time import sleep
import warnings
import os
from selenium.webdriver.support.ui import Select
from selenium.webdriver.support.ui import WebDriverWait

warnings.filterwarnings('ignore')

import io
chrome_options = webdriver.ChromeOptions()
# chrome_options.add_experimental_option('prefs', prefs)
chrome_options.add_argument('--kiosk-printing')
# chrome_options.add_argument('--headless')
chrome_options.add_argument('log-level=3')
# chrome_options.add_argument('--disable-gpu')
chrome_options.add_argument("--window-size=1920,1080")

#! pip install easyocr
# ! pip install undetected_chromedriver

import easyocr
import PIL
from PIL import Image 
import numpy as np
import requests
import time
import undetected_chromedriver as uc

In [38]:

options = webdriver.ChromeOptions() 
options.headless = False
driver = webdriver.Chrome(options=options)
wait = WebDriverWait(driver, 10)

driver.get("https://online.eregistrationukgov.in/e_search/Frm_vill_Wise.aspx#")

from selenium.webdriver.support.select import Select
District = []

driver.find_element(By.XPATH,'//*[@id="MainContent_ddl_dis"]').click()
select = Select(driver.find_element(By.XPATH,'//*[@id="MainContent_ddl_dis"]'))
for opt in select.options:
    District.append([opt.text,opt.get_attribute("value")])

District.pop(0)    

District_id = []
for i in District:
    District_id.append(i[1])

District_name = []
for i in District:
    District_name.append(i[0])

SRO = []
Village1 = []
Final_list = []

for dist in District[3:13]:
    driver.find_element(By.XPATH,'//*[@id="MainContent_ddl_dis"]').click()
    select = Select(driver.find_element(By.XPATH,'//*[@id="MainContent_ddl_dis"]'))
    select.select_by_visible_text(dist[0])
    b = dist[0]
    a = dist[1]
    
    sleep (2)
    
    SRO = []
    WebDriverWait(driver, 20).until(EC.element_to_be_clickable((By.XPATH, "//*[@id='MainContent_ddl_sro']")))
    driver.implicitly_wait(2)
    driver.find_element(By.XPATH,'//*[@id="MainContent_ddl_sro"]').click()
    select = Select(driver.find_element(By.XPATH,'//*[@id="MainContent_ddl_sro"]'))
    for opt in select.options:
        SRO.append([opt.text,opt.get_attribute("value")])
    SRO.pop(0)
    
    SRO_id = []
    for i in SRO:
        SRO_id.append(i[1])

    SRO_name = []
    for i in SRO:
        SRO_name.append(i[0])
        
    for sr in SRO:
        driver.find_element(By.XPATH,'//*[@id="MainContent_ddl_sro"]').click()
        select = Select(driver.find_element(By.XPATH,'//*[@id="MainContent_ddl_sro"]'))
        select.select_by_visible_text(sr[0])
        d = sr[0]
        c = sr[1]
        
        sleep(2)
        
        year = []
        
        driver.find_element(By.XPATH,'//*[@id="MainContent_dd_regyear"]').click()
        select = Select(driver.find_element(By.XPATH,'//*[@id="MainContent_dd_regyear"]'))
        for opt in select.options:
            year.append([opt.text,opt.get_attribute("value")])
        year.pop(0)
#         print(year)
        select.select_by_visible_text(year[-2][1])
        
        sleep(2)
        
        Village = []
        
        WebDriverWait(driver, 20).until(EC.element_to_be_clickable((By.XPATH, "//*[@id='MainContent_dd_vill']")))
        driver.implicitly_wait(2)
        driver.find_element(By.XPATH,'//*[@id="MainContent_dd_vill"]').click()
        select = Select(driver.find_element(By.XPATH,'//*[@id="MainContent_dd_vill"]'))
        for opt in select.options:
            Village.append([opt.text,opt.get_attribute("value")])
        Village.pop(0)

        Village_id = []
        for i in Village:
            Village_id.append(i[1])

        Village_name = []
        for i in SRO:
            Village_name.append(i[0])
            
        for vil in Village:
            f = vil[0]
            e = vil[1]
            Final_list.append([a,b,c,d,e,f])
        
        print(a,b,c,d)
        sleep(0.5)

04 DEHRADUN 08 CHAKRATA
04 DEHRADUN 09 MUSSOORIE
04 DEHRADUN 51 DEHRADUN
04 DEHRADUN 05 RISHIKESH
04 DEHRADUN 52 VIKASNAGAR
04 DEHRADUN 00 DR, DEHRADUN
04 DEHRADUN 12 Dehradun 3rd Old
05 PAURI GARHWAL 01 KOTDWAR
05 PAURI GARHWAL 03 PAURI
05 PAURI GARHWAL 04 SRINAGAR
05 PAURI GARHWAL 02 LANSDOWNE
06 CHOMOLI 02 JOSHIMATH
06 CHOMOLI 01 CHAMOLI
06 CHOMOLI 03 KARANPRAYAG
06 CHOMOLI 04 THARALI
07 HARIDWAR 51 HARIDWAR
07 HARIDWAR 03 LAKSAR
07 HARIDWAR 52 ROORKEE
08 NAINITAL 05 DHARI
08 NAINITAL 51 HALDWANI
08 NAINITAL 03 NAINITAL
08 NAINITAL 04 RAMNAGAR
09 TEHRI GARHWAL 04 TEHRI
09 TEHRI GARHWAL 01 DEVPRAYAG
09 TEHRI GARHWAL 03 JAKHNIDHAR
09 TEHRI GARHWAL 02 GHANSALI
10 PITHORAGARH 03 PITHORAGARH
10 PITHORAGARH 02 GANGOLIHAT
10 PITHORAGARH 01 DIDIHAT
10 PITHORAGARH 04 DHARCHULA
10 PITHORAGARH 05 MUNSYARI
11 RUDRAPRAYAG 01 RUDRAPRAYAG
11 RUDRAPRAYAG 02 UKHIMATH
12 U S NAGAR 06 RUDRAPUR
12 U S NAGAR 01 BAZPUR
12 U S NAGAR 02 JASPUR
12 U S NAGAR 03 KASHIPUR
12 U S NAGAR 04 KICHHA
12 U S NAGAR 05 SITARGANJ
13 UTTARKASHI 01 BARKOT
13 UTTARKASHI 02 PUROLA
13 UTTARKASHI 03 UTTARKASHI

In [27]:
# District = pd.DataFrame(District)
# District.to_csv('District.csv')

In [39]:
# print(Final_list)
Final_list = pd.DataFrame(Final_list)
print(Final_list)

        0           1   2           3  \
0      04    DEHRADUN  08    CHAKRATA
1      04    DEHRADUN  08    CHAKRATA
2      04    DEHRADUN  08    CHAKRATA
3      04    DEHRADUN  08    CHAKRATA
4      04    DEHRADUN  08    CHAKRATA
...    ..         ...  ..         ...
18434  13  UTTARKASHI  03  UTTARKASHI
18435  13  UTTARKASHI  03  UTTARKASHI
18436  13  UTTARKASHI  03  UTTARKASHI
18437  13  UTTARKASHI  03  UTTARKASHI
18438  13  UTTARKASHI  03  UTTARKASHI

                                                       4  \
0                                             कोटी कनासर
1                                    कोरुवा तहसील चकराता
2                                     मलेथा तहसील चकराता
3                                      लखवार तहसील कालसी
4                                     विसाहल तहसील कालसी
...                                                  ...
18434                                             हर्षिल
18435  हाईडिल कालोनी   -2.B-3 धरासू गंगोत्री राष्ट्री...
18436                                     हिटाणूमय भालसी
18437                                               हिना
18438  हीना  -5.E-2 धरासू - गंगोत्री राष्ट्रीय राजमार...

                                                       5
0                                             कोटी कनासर
1                                    कोरुवा तहसील चकराता
2                                     मलेथा तहसील चकराता
3                                      लखवार तहसील कालसी
4                                     विसाहल तहसील कालसी
...                                                  ...
18434                                             हर्षिल
18435  हाईडिल कालोनी -2.B-3 धरासू गंगोत्री राष्ट्रीय ...
18436                                     हिटाणूमय भालसी
18437                                               हिना
18438  हीना -5.E-2 धरासू - गंगोत्री राष्ट्रीय राजमार्...

[18439 rows x 6 columns]

In [40]:
# Final_list.to_csv('Final_list2.csv')

In [41]:
Final_list.columns = ['District_id','District_name','SRO_id','SRO_name','Village_id','Village_name']

In [42]:
Final_list1 = Final_list.copy()

In [43]:
print(Final_list1)

      District_id District_name SRO_id    SRO_name  \
0              04      DEHRADUN     08    CHAKRATA
1              04      DEHRADUN     08    CHAKRATA
2              04      DEHRADUN     08    CHAKRATA
3              04      DEHRADUN     08    CHAKRATA
4              04      DEHRADUN     08    CHAKRATA
...           ...           ...    ...         ...
18434          13    UTTARKASHI     03  UTTARKASHI
18435          13    UTTARKASHI     03  UTTARKASHI
18436          13    UTTARKASHI     03  UTTARKASHI
18437          13    UTTARKASHI     03  UTTARKASHI
18438          13    UTTARKASHI     03  UTTARKASHI

                                              Village_id  \
0                                             कोटी कनासर
1                                    कोरुवा तहसील चकराता
2                                     मलेथा तहसील चकराता
3                                      लखवार तहसील कालसी
4                                     विसाहल तहसील कालसी
...                                                  ...
18434                                             हर्षिल
18435  हाईडिल कालोनी   -2.B-3 धरासू गंगोत्री राष्ट्री...
18436                                     हिटाणूमय भालसी
18437                                               हिना
18438  हीना  -5.E-2 धरासू - गंगोत्री राष्ट्रीय राजमार...

                                            Village_name
0                                             कोटी कनासर
1                                    कोरुवा तहसील चकराता
2                                     मलेथा तहसील चकराता
3                                      लखवार तहसील कालसी
4                                     विसाहल तहसील कालसी
...                                                  ...
18434                                             हर्षिल
18435  हाईडिल कालोनी -2.B-3 धरासू गंगोत्री राष्ट्रीय ...
18436                                     हिटाणूमय भालसी
18437                                               हिना
18438  हीना -5.E-2 धरासू - गंगोत्री राष्ट्रीय राजमार्...

[18439 rows x 6 columns]

In [44]:
# Final_list1[["Village_name", "Village_id"]] = Final_list1["Village"].apply(lambda x: pd.Series(str(x).split(",")))
# Final_list1[["Zone_name",'Zone_id']] = Final_list1["Zone"].str.split(',', expand=True)
# Final_list1[["District_name",'District_id']] = Final_list1["District"].str.split(',', expand=True)
# Final_list1[["SRO_name",'SRO_id']] = Final_list1["SRO"].str.split(',', expand=True)

In [45]:
list3 = pd.read_excel(r"D:\Data\UK\UK_Disctrict_SRO_Village_list.xlsx")
list3

,Unnamed: 0,District_id,District_name,SRO_id,SRO_name,Village_id,Village_name
0,0,1,ALMORA,3,RANIKHET,Adarsh Ariya,Adarsh Ariya
1,1,1,ALMORA,3,RANIKHET,Chiliyanaula Bazar,Chiliyanaula Bazar
2,2,1,ALMORA,3,RANIKHET,Hedakhan ward,Hedakhan ward
3,3,1,ALMORA,3,RANIKHET,kalikholi,kalikholi
4,4,1,ALMORA,3,RANIKHET,kanar,kanar
...,...,...,...,...,...,...,...
2356,2356,3,CHAMPAWAT,1,CHAMPAWAT,सिलाड -15.O.29 चम्पावत टनकपुर राष्ट्रीय राजमा...,सिलाड -15.O.29 चम्पावत टनकपुर राष्ट्रीय राजमार...
2357,2357,3,CHAMPAWAT,1,CHAMPAWAT,सीमाड़,सीमाड़
2358,2358,3,CHAMPAWAT,1,CHAMPAWAT,हरम,हरम
2359,2359,3,CHAMPAWAT,1,CHAMPAWAT,होलीपिपलाटी,होलीपिपलाटी
2360,2360,3,CHAMPAWAT,1,CHAMPAWAT,"होलीपिपलाटी, तहसील पाटी, जनपद चम्पावत","होलीपिपलाटी, तहसील पाटी, जनपद चम्पावत"

In [46]:
list3 = list3.drop(['Unnamed: 0'], axis=1)
list3

,District_id,District_name,SRO_id,SRO_name,Village_id,Village_name
0,1,ALMORA,3,RANIKHET,Adarsh Ariya,Adarsh Ariya
1,1,ALMORA,3,RANIKHET,Chiliyanaula Bazar,Chiliyanaula Bazar
2,1,ALMORA,3,RANIKHET,Hedakhan ward,Hedakhan ward
3,1,ALMORA,3,RANIKHET,kalikholi,kalikholi
4,1,ALMORA,3,RANIKHET,kanar,kanar
...,...,...,...,...,...,...
2356,3,CHAMPAWAT,1,CHAMPAWAT,सिलाड -15.O.29 चम्पावत टनकपुर राष्ट्रीय राजमा...,सिलाड -15.O.29 चम्पावत टनकपुर राष्ट्रीय राजमार...
2357,3,CHAMPAWAT,1,CHAMPAWAT,सीमाड़,सीमाड़
2358,3,CHAMPAWAT,1,CHAMPAWAT,हरम,हरम
2359,3,CHAMPAWAT,1,CHAMPAWAT,होलीपिपलाटी,होलीपिपलाटी
2360,3,CHAMPAWAT,1,CHAMPAWAT,"होलीपिपलाटी, तहसील पाटी, जनपद चम्पावत","होलीपिपलाटी, तहसील पाटी, जनपद चम्पावत"

In [47]:
list3 = pd.concat([list3,Final_list1],ignore_index=True)
list3

,District_id,District_name,SRO_id,SRO_name,Village_id,Village_name
0,1,ALMORA,3,RANIKHET,Adarsh Ariya,Adarsh Ariya
1,1,ALMORA,3,RANIKHET,Chiliyanaula Bazar,Chiliyanaula Bazar
2,1,ALMORA,3,RANIKHET,Hedakhan ward,Hedakhan ward
3,1,ALMORA,3,RANIKHET,kalikholi,kalikholi
4,1,ALMORA,3,RANIKHET,kanar,kanar
...,...,...,...,...,...,...
20795,13,UTTARKASHI,03,UTTARKASHI,हर्षिल,हर्षिल
20796,13,UTTARKASHI,03,UTTARKASHI,हाईडिल कालोनी -2.B-3 धरासू गंगोत्री राष्ट्री...,हाईडिल कालोनी -2.B-3 धरासू गंगोत्री राष्ट्रीय ...
20797,13,UTTARKASHI,03,UTTARKASHI,हिटाणूमय भालसी,हिटाणूमय भालसी
20798,13,UTTARKASHI,03,UTTARKASHI,हिना,हिना
20799,13,UTTARKASHI,03,UTTARKASHI,हीना -5.E-2 धरासू - गंगोत्री राष्ट्रीय राजमार...,हीना -5.E-2 धरासू - गंगोत्री राष्ट्रीय राजमार्...

In [49]:
list3.to_excel('UK_Disctrict_SRO_Village_list.xlsx')